### ISSUE TITLE
The unit of file size

### ISSUE THREAD

**Issue by allenyllee** [yuri0sh/code-size#1]
Hi, thanks for you develop this extension!
I've found some issue about the file size unit.

Below is the size shown in your extension: 
<img width="585" alt="Snipaste_2023-12-29_16-54-06" src="https://github.com/yuri0sh/code-size/assets/3991134/a5a54543-4ee0-4873-afa8-00ee28105ca5">
you treat 1 MB as 10^6 bytes.

But on Windows, it treats 1 MB as 2^20 bytes:
<img width="312" alt="Snipaste_2023-12-29_16-56-25" src="https://github.com/yuri0sh/code-size/assets/3991134/69a194b6-f751-483b-ae19-42a3bf9eb454">

Actually, the unit used on Windows is MiB, 1 MiB = 2^20 bytes.

Can you provide a switch that can toggle between MiB and MB, so that we can compare the file size under different OS? Thanks!

**Comment by hamirmahal** [comment]
I would also like this feature.

**Comment by yuri0sh** [comment]
Added `size.fileSizeUnits` config option (https://github.com/yuri0sh/code-size/commit/1843150e6d93eedad2b2eaadeb1f1a02fd2c3770)

Included in 0.3.0 release

**Comment by yuri0sh** [comment]
Thank you!
